import{a as q,S as w,i}from"./assets/vendor-CucEYOFD.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();const v="56828083-7e4521b63d087d0b33cd2b929",P="https://pixabay.com/api/";async function u(t,o=1){const a={key:v,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:15};return(await q.get(P,{params:a})).data}const m=document.querySelector(".gallery");document.querySelector(".loader");document.querySelector(".load-more-btn");let $=new w(".gallery a",{captionsData:"alt",captionDelay:250});function f(t){const o=t.map(({webformatURL:a,largeImageURL:s,tags:e,likes:r,views:n,comments:L,downloads:S})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info-container">
        <p class="info-item"><b>Likes</b><br>${r}</p>
        <p class="info-item"><b>Views</b><br>${n}</p>
        <p class="info-item"><b>Comments</b><br>${L}</p>
        <p class="info-item"><b>Downloads</b><br>${S}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",o),$.refresh()}function B(){m.innerHTML=""}function y(){document.querySelector(".loader").classList.remove("is-hidden")}function g(){document.querySelector(".loader").classList.add("is-hidden")}function M(){document.querySelector(".load-more-btn").classList.remove("is-hidden")}function d(){document.querySelector(".load-more-btn").classList.add("is-hidden")}const h=document.querySelector(".search-form"),E=document.querySelector(".load-more-btn");let l="",c=1,p=0;h.addEventListener("submit",O);E.addEventListener("click",C);async function O(t){t.preventDefault();const o=t.target.elements.searchQuery.value.trim();if(!o){i.warning({message:"Please enter a search query!"});return}l=o,c=1,B(),d(),y();try{const a=await u(l,c);if(p=a.totalHits,a.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!"});return}f(a.hits),b()}catch(a){i.error({message:`Something went wrong: ${a.message}`})}finally{g(),h.reset()}}async function C(){c+=1,d(),y();try{const t=await u(l,c);f(t.hits),H(),b()}catch(t){i.error({message:`Error loading more images: ${t.message}`})}finally{g()}}function b(){c*15>=p?(d(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomCenter"})):M()}function H(){const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
